### ISSUE TITLE
bug; chain grpc port not exposed properly

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#116]
Chains grpc ports are not enabled and also not exposed properly to other resources in the cluster.

## How to reproduce?
Run with newwer hermes relayer version 1.5.1, using the grpc endpoints

**Comment by kruspy** [comment]
Looks like the issue is that gRPC port listens on localhost, preventing Hermes to reach it and build the client successfully.

Updating it solves the issue:

`sed -i -e 's#"localhost:9090"#"0.0.0.0:9090"#g' $CHAIN_DIR/config/app.toml`
