### ISSUE TITLE
bug: `0.1.34` does not seem to work with Mac M1

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#121]
## Overview
Currently release `0.1.34` is not working with Mac M1, as it is trying to pull image with `--platform linux/arm64`

## Proposal
Build all images with platform `--platform linux/arm64`. All images would need to support arm docker images in that case.

**Comment by Anmol1696** [comment]
Somehow `0.1.32` seems to be working regardless of it having docker image with amd platform.
Maybe alternative would be to fix the digest of the image and force k8s on mac to pull nad run docker images with amd platform

**Comment by nabaruns** [comment]
Yes, facing issue with 0.1.32 as well on mac.

**Comment by Anmol1696** [comment]
@nabaruns You can now try and run `0.1.36` version on your mac, that should run now.
We added support for all the chains to have arm support and some of the glue code and images as well.

Let me know if you face the issue again, can re-open the issue. There are still 2 components that I have not  ported to Mac, but they are simple `go_image`: `exposer` and `registry`. If you see any issue, let me know.
