### ISSUE TITLE
examples: Add cosmjs setup scripts to run external setup

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#13]
## Overview
Given that the cluster is up and running, current expectations for setup state of the whole ecosystem is to be done externally. We need to create `examples/` where we are creating following examples of scripts
* Create osmos/ibc token pools
* Run upgrade, pre-upgrade and post upgrade

These are similar to *test setups*

## Design
A cosmjs script that will read the `values.yaml` file to figure out the client it needs to create based on the `chains` key. In the testing setup the script can be seperated out in way where we can run js scripts individually as well, and in a composible state.

### Functional requirements
* these will be setup scripts, they may or maynot have asserts 
* Scripts are currenty should be run against the cluster, which is already running
* Maybe we have `values.yaml` itself also generated inside the cosmjs scripts.

**Note: Need a good structure for the scripts, need cosmjs examples itself that we can be using for standarization**

**Comment by pyramation** [comment]
epic! 🙌🏻

**Comment by Anmol1696** [comment]
Done in `examples/osmojs/src`
