### ISSUE TITLE
docs: wrong title

### ISSUE THREAD

**Issue by liujun93** [cosmology-tech/starship#271]
1. the `Step 4` in title should be changed to `Step 5`?

https://starship.cosmology.tech/get-started/step-5

![image](https://github.com/cosmology-tech/starship/assets/44238025/3e429ce2-17c2-418e-99c6-c0d412c89908)

2. `Nextra` here need to be removed

<img width="197" alt="image" src="https://github.com/cosmology-tech/starship/assets/44238025/2830be17-4e26-426c-b1e9-a384574d94b6">

4. Extra **```bash** in the code block

https://github.com/cosmology-tech/starship/tree/main/examples/getting-started

<img width="769" alt="image" src="https://github.com/cosmology-tech/starship/assets/44238025/4abc6227-0bfd-49b1-94b8-ce233b20b61e">

**Comment by Anmol1696** [comment]
@liujun93 for 2., how or where do i remove `Nextra`? I tried to search for it, but was not able to find out where it originates from.
