### ISSUE TITLE
starshipjs merge

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/starship#435]
- [ ] remove `kindCluster`, this will allow us to have a single config (no .local, or .prod, etc) https://github.com/osmosis-labs/osmojs/blob/c2ea810d5856f8d32d42fc8be3f3a3ec2d0961da/packages/osmojs/package.json#L31-L37

https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/package.json

- [ ] remove all `kind` deps
- [ ] update in package.json files, any links to github so it points to starship, not starshipjs
- [ ] move everything except `clients/` and `.github/` to `starship/`
- [ ] move rename `clients/js/starshipjs` to `clients/js`

**Comment by Anmol1696** [comment]
Done.
