### ISSUE TITLE
bug: starship-cli stop command returns before pods are actually stopped

### ISSUE THREAD

**Issue by Kayanski** [cosmology-tech/starship#584]
When running `starship stop`  on the starship cli, the command returns before all pods are effectively stopped. 
Just like the `starship start` command returns only when pods are all started, I suggest the stop command should do the same. 

What do you think ?

**Comment by Anmol1696** [comment]
Hmm good idea. 
Let me figure this out, should be an easier fix now, we have a way to determine pods in terminating state.

**Comment by Anmol1696** [comment]
Newest release of the cli has this feature now.
